
spring:
  application:
    name: ms-proposta
  profiles:
    active: DOCKER
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: true

  datasource:
    url: jdbc:h2:file:./proposta
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.globally_quoted_identifiers: false
      hibernate.show_sql: true
      hibernate.format_sql: true